Updated source.fixAll.eslint to explicit
JoshuaKGoldberg/create-typescript-app pull request #1110
Opened 2023-12-22 07:00 UTC by PraveenShinde3

## PR Checklist

- [x] Addresses an existing open issue: fixes #1105 
- [x] That issue was marked as [`status: accepting prs`](https://github.com/JoshuaKGoldberg/create-typescript-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22status%3A+accepting+prs%22)
- [x] Steps in [CONTRIBUTING.md](https://github.com/JoshuaKGoldberg/create-typescript-app/blob/main/.github/CONTRIBUTING.md) were taken

## Overview

Updated source.fixAll.eslint to "explicit"

![image](https://github.com/JoshuaKGoldberg/create-typescript-app/assets/107350270/08c05bfa-33db-4014-b32e-486c8a97fed8)

2023-12-22 07:27 UTC, JoshuaKGoldberg requested changes
A start 🙌

2023-12-22 07:27 UTC, JoshuaKGoldberg commented on src/steps/writing/creation/dotVSCode.ts
[Bug] Thanks for sending this in! I think you missed a line from the original issue 🙂:

> Note that you'll need to update any file that mentions `source.fixAll.eslint`. See `.vscode/settings.json`.

This repo's own `.vscode/settings.json` also needs to be updated.

2023-12-22 07:42 UTC, PraveenShinde3 commented on src/steps/writing/creation/dotVSCode.ts
I have updated this ```.vscode/settings.json``` in my local but forgot to commit it, will make the changes, 

Also, I could see only in 2 files this ```source.fixAll.eslint``` is used i.e ```.vscode/settings.json``` and in ```src\steps\writing\creation\dotVSCode.ts```.

2023-12-22 07:45 UTC, PraveenShinde3 commented on src/steps/writing/creation/dotVSCode.ts
@JoshuaKGoldberg I have made the changes please review it once

2023-12-22 17:44 UTC, JoshuaKGoldberg commented on src/steps/writing/creation/dotVSCode.ts
Cool yup looks like those are the only two places. Great!

2023-12-22 18:08 UTC, JoshuaKGoldberg requested changes
Cool, looks really close to merge! Just a couple of touchups 🙂

2023-12-22 18:08 UTC, JoshuaKGoldberg commented on .vscode/settings.json
Tip: _**[Compliance / compliance](https://github.com/JoshuaKGoldberg/create-typescript-app/actions/runs/7297483775/job/19901224413?pr=1110)**_ is failing because: _"This PR's title should conform to specification at https://conventionalcommits.org/"_. You'll want to switch the title to look like `feat: updated etc. etc.`. See recently merged PRs that have `fix:` in the title for other examples.

#574 tracks doing that automatically.

2023-12-23 06:57 UTC, PraveenShinde3 commented on .vscode/settings.json
I have made the changes

2023-12-24 01:21 UTC, JoshuaKGoldberg approved these changes
Swell, thanks!

<img alt="Stop-motion sheep giving two thumbs up" src="https://media4.giphy.com/media/tIeCLkB8geYtW/giphy.gif"/>

2023-12-24 01:21 UTC, merged

2023-12-24 01:22 UTC, JoshuaKGoldberg commented
@all-contributors please add @praveenshinde3 for code.

> 🤖 Beep boop! This comment was added automatically by [all-contributors-auto-action](https://github.com/marketplace/actions/all-contributors-auto-action).
> Not all contributions can be detected from Git & GitHub alone. Please comment any missing contribution types this bot missed.
> ...and of course, thank you for contributing! 💙