fix: exclude tests with.npmignore
JoshuaKGoldberg/create-typescript-app pull request #1637
Opened 2024-08-15 17:49 UTC by johnnyreilly

## PR Checklist

- [x] Addresses an existing open issue: fixes #1629 
- [x] That issue was marked as [`status: accepting prs`](https://github.com/JoshuaKGoldberg/create-typescript-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22status%3A+accepting+prs%22)
- [x] Steps in [CONTRIBUTING.md](https://github.com/JoshuaKGoldberg/create-typescript-app/blob/main/.github/CONTRIBUTING.md) were taken

## Overview

Doing this on a mobile phone on a train. It can never work, can it?

2024-08-16 02:20 UTC, JoshuaKGoldberg commented on .npmignore
This'll need to be added to the files generated in new repos too, I'm afraid. Just adding it here only works for this repo.

2024-08-16 02:21 UTC, JoshuaKGoldberg approved these changes
A start! ✨

2024-08-16 05:29 UTC, johnnyreilly commented on .npmignore
Ah right - makes sense! Whereabouts would that change be made? (I'm heading off on holiday today so I may have to address this when I return)

2024-08-16 14:01 UTC, JoshuaKGoldberg commented on .npmignore
[`src/steps/writing/creation/rootFiles.ts`](https://github.com/JoshuaKGoldberg/create-typescript-app/blob/d2f6a1f89389d5ea81581c004034329ff84cafb8/src/steps/writing/creation/rootFiles.ts) is a good starter. `.gitignore` is a rough equivalent, so you could search for that & `createDotGitignore`.

2024-08-16 15:42 UTC, JoshuaKGoldberg requested changes
(wrong button)

2024-08-16 20:00 UTC, johnnyreilly commented on .npmignore
Thanks! Will check in when back from hols

2024-08-24 09:56 UTC, johnnyreilly commented
Okay think this is good!

2024-08-24 16:52 UTC, JoshuaKGoldberg approved these changes
Yup, this is great - thanks!

I was actually a little surprised at first it's passing build, there are no unit test changes... But all is well:
* Unit tests: I never added snapshots for `rootFiles.ts` because they'd be super verbose.
* End-to-end tests: the migration one is verifying that the `.npmignore` on disk matches what's created

✅ great!

2024-08-24 16:52 UTC, merged