docs: clarify the purpose of --bin
JoshuaKGoldberg/create-typescript-app pull request #1683
Opened 2024-11-09 18:34 UTC by johnnyreilly

## PR Checklist

- [x] Addresses an existing open issue: fixes #1677
- [x] That issue was marked as [`status: accepting prs`](https://github.com/JoshuaKGoldberg/create-typescript-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22status%3A+accepting+prs%22)
- [x] Steps in [CONTRIBUTING.md](https://github.com/JoshuaKGoldberg/create-typescript-app/blob/main/.github/CONTRIBUTING.md) were taken

## Overview

Clarify what `bin` does and does not do.

2024-11-10 20:14 UTC, JoshuaKGoldberg requested changes
A start! WDYT?

2024-11-10 20:14 UTC, JoshuaKGoldberg commented on docs/Options.md
> +- `--bin` _(`string`)_: `package.json` bin value to include for npx-style running. (eg `"./bin/index.js"`) - this does not create any of folders or files; just references to them in the `package.json
🤔 This is a lot of text for a list item, and still doesn't really cover the nuance or recommended usage here. How about:

* Trimming this down a bit to more precisely just describe it as a `package.json` bin property string
* Writing an FAQ with more information & suggested way to do it

? That way we get the idea of _"export a `bin()`"_ suggested to users, without forcing them to do anything.

```suggestion
- `--bin` _(`string`)_: value to set in `package.json`'s `"bin"` property, per [FAQs > How can I use `bin`?]( ... )
```

2024-11-11 18:42 UTC, johnnyreilly commented
There - any good?

2024-11-11 18:47 UTC, JoshuaKGoldberg approved these changes
Great, thanks! 🙌 

Just one nit that I can apply and then merge. Yay!

2024-11-11 18:47 UTC, JoshuaKGoldberg commented on docs/FAQs.md
> +If you'd like an example of what that looks like, just take a look at the [CTA source code](https://github.com/JoshuaKGoldberg/create-typescript-app/blob/e7fafcb8968f8f6c551ab0917c9a6a849a3cba28/bin/
```suggestion
If you'd like an example of what that looks like, take a look at the [CTA source code](https://github.com/JoshuaKGoldberg/create-typescript-app/blob/e7fafcb8968f8f6c551ab0917c9a6a849a3cba28/bin/index.js)!
```

https://tipsforteachers.substack.com/p/59-stop-saying-the-word-just?open=false#%C2%A7a-tip-to-try-in-class-this-week

2024-11-11 18:56 UTC, merged

2024-11-11 19:07 UTC, johnnyreilly commented
@JoshuaKGoldberg this is .... un-just 😉